# Generated by Django 5.1.15 on 2025-12-09 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PLA_SILK', 'PLA Silk'), ('PETG', 'PETG'), ('PLA_MATE', 'PLA Mate')], max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('stock_gramos', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('peso_gramos', models.FloatField()),
                ('archivo_stl', models.FileField(blank=True, null=True, upload_to='stls/')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.filamento')),
            ],
        ),
        migrations.CreateModel(
            name='ComposicionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.pieza')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('piezas', models.ManyToManyField(through='inventario.ComposicionProducto', to='inventario.pieza')),
            ],
        ),
        migrations.AddField(
            model_name='composicionproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
        ),
    ]
