# Generated by Django 5.1.15 on 2025-12-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filamento',
            name='stock_gramos',
        ),
        migrations.AddField(
            model_name='filamento',
            name='cantidad_rollos',
            field=models.PositiveIntegerField(default=0, verbose_name='Rollos Cerrados (1kg)'),
        ),
        migrations.AddField(
            model_name='filamento',
            name='gramos_sueltos',
            field=models.FloatField(default=0, verbose_name='Gramos en carrete abierto'),
        ),
        migrations.AlterField(
            model_name='filamento',
            name='tipo',
            field=models.CharField(choices=[('PLA_SILK', 'PLA Silk'), ('PETG', 'PETG'), ('PLA_MATE', 'PLA Mate'), ('PLA', 'pla')], max_length=50),
        ),
    ]
