# Generated by Django 5.1.15 on 2025-12-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_filamento_stock_gramos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='stock_fisico',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock impreso (Unidades)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_armado',
            field=models.PositiveIntegerField(default=0, verbose_name='Molinos Listos'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ventas',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Vendidos'),
        ),
    ]
