# Generated by Django 5.1.15 on 2025-12-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_pieza_stock_fisico_producto_stock_armado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='piezas/', verbose_name='Foto de la pieza'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Foto del producto final'),
        ),
    ]
