# Generated by Django 5.1.15 on 2025-12-10 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_pieza_imagen_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono / WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección de Envío')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', '🔴 Pendiente de Pago'), ('PARCIAL', '🟡 Pago Parcial (Seña)'), ('PAGADO', '🟢 Pagado Totalmente')], default='PENDIENTE', max_length=20)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Abonado (S/)')),
                ('estado_entrega', models.CharField(choices=[('PREPARACION', '📦 En Preparación'), ('TRANSITO', '🚚 En Tránsito / Enviado'), ('ENTREGADO', '✅ Entregado al Cliente')], default='PREPARACION', max_length=20)),
                ('codigo_seguimiento', models.CharField(blank=True, help_text='Número de guía o tracking', max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio al momento de la venta', max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.pedido')),
            ],
        ),
    ]
