# Generated by Django 5.1.15 on 2025-12-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_cliente_pedido_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='archivo_gcode',
            field=models.FileField(blank=True, null=True, upload_to='gcodes/', verbose_name='Archivo GCode'),
        ),
    ]
