# Generated by Django 5.1.15 on 2025-12-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_pieza_archivo_gcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='cubierta',
            field=models.BooleanField(default=True, verbose_name='lleva cubierta?'),
        ),
    ]
