# Generated by Django 5.1.15 on 2025-12-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_itempedido_cubierta'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='ficha_descriptiva',
            field=models.BooleanField(default=True, verbose_name='lleva ficha tecnica?'),
        ),
        migrations.AlterField(
            model_name='filamento',
            name='tipo',
            field=models.CharField(choices=[('PLA_SILK', 'PLA Silk'), ('PETG', 'PETG'), ('PLA_MATE', 'PLA Mate'), ('PLA', 'PLA')], max_length=50),
        ),
    ]
