# Generated by Django 5.1.15 on 2025-12-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_itempedido_ficha_descriptiva_alter_filamento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='requiere_factura',
            field=models.BooleanField(default=False, verbose_name='Solicitó Factura'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='cubierta',
            field=models.BooleanField(default=True, verbose_name='¿Lleva cubierta?'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='ficha_descriptiva',
            field=models.BooleanField(default=True, verbose_name='¿Lleva ficha técnica?'),
        ),
        migrations.AlterField(
            model_name='pieza',
            name='peso_gramos',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso (g)'),
        ),
    ]
