# Generated by Django 5.1.15 on 2025-12-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_pedido_requiere_factura_alter_itempedido_cubierta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('archivo_3mf', models.FileField(upload_to='logos/models/')),
                ('image', models.ImageField(upload_to='logos/images/')),
            ],
        ),
    ]
