# Generated by Django 5.1.15 on 2025-12-14 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='ficha_descriptiva',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.logo'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='archivo_3mf',
            field=models.FileField(blank=True, null=True, upload_to='logos/models/'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='logos/images/'),
        ),
    ]
