# Generated by Django 5.1.15 on 2025-12-14 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_remove_itempedido_ficha_descriptiva_itempedido_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='texto_dedicatoria',
            field=models.TextField(blank=True, help_text="Ej: 'Recuerdo de la Gerencia de Mantenimiento 2025'", null=True),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.logo'),
        ),
    ]
