# Generated by Django 5.1.15 on 2025-12-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_itempedido_texto_dedicatoria_alter_itempedido_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_entrega',
            field=models.CharField(choices=[('COLA', '⏳ En Cola (Pendiente)'), ('TALLER', '🔨 En Taller (Fabricación)'), ('TRANSITO', '🚚 En Tránsito'), ('ENTREGADO', '✅ Entregado y Conforme')], default='COLA', max_length=20),
        ),
    ]
