# Generated by Django 5.1.15 on 2025-12-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_alter_pedido_estado_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='es_urgente',
            field=models.BooleanField(default=False, verbose_name='¿Es Urgente?'),
        ),
    ]
