# Generated by Django 5.1.15 on 2026-01-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_pedido_es_urgente'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='nombre',
            field=models.TextField(blank=True, verbose_name='Dirección de Envío'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='poner_nombre',
            field=models.BooleanField(default=True, verbose_name='¿Lleva nombre?'),
        ),
    ]
