# Generated by Django 5.1.15 on 2026-01-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_itempedido_nombre_itempedido_poner_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento (S/)'),
        ),
    ]
