# Generated by Django 5.1.15 on 2026-01-27 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_itempedido_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_entrega',
            field=models.CharField(choices=[('VENTA', '💰 Venta/Cotización (No pasar a Taller aún)'), ('COLA', '⏳ En Cola de Taller (Listo para fabricar)'), ('PROCESO', '🔨 En Proceso (Taller trabajando)'), ('LISTO', '📦 Listo para Retiro (Taller terminó)'), ('ENTREGADO', '✅ Entregado al Cliente')], default='VENTA', max_length=20),
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('DISENO', '🎨 Fase de Diseño'), ('PRUEBA', '🧪 Pruebas / Prototipo'), ('PRODUCCION', '🔨 En Producción'), ('TERMINADO', '✅ Terminado (Evaluar Producto)')], default='DISENO', max_length=20)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='proyectos/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.cliente')),
            ],
        ),
    ]
