# Generated by Django 5.1.15 on 2026-01-27 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_alter_pedido_estado_entrega_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPiezaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, help_text='Pon 0 si es garantía o regalo', max_digits=10, verbose_name='Precio (S/)')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_pieza', to='inventario.pedido')),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.pieza')),
            ],
        ),
    ]
