# Generated by Django 5.1.15 on 2026-01-27 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_itempiezapedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.cliente'),
        ),
    ]
