# Generated by Django 5.1.15 on 2026-02-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_alter_proyecto_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='filamento',
            name='costo_rollo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo por Rollo (S/)'),
        ),
    ]
