# Generated by Django 5.1.15 on 2026-02-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_filamento_costo_rollo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='tiempo_impresion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tiempo de Impresión'),
        ),
    ]
