# Generated by Django 5.1.15 on 2026-02-04 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_pieza_tiempo_impresion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock Disponible')),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Unitario (S/)')),
                ('unidad', models.CharField(default='unidad', max_length=20, verbose_name='Unidad de Medida')),
                ('link_compra', models.URLField(blank=True, null=True, verbose_name='Link de Compra')),
            ],
        ),
        migrations.CreateModel(
            name='ComposicionInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('es_opcional', models.BooleanField(default=False, verbose_name='Es Opcional')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.insumo')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='insumos',
            field=models.ManyToManyField(through='inventario.ComposicionInsumo', to='inventario.insumo'),
        ),
    ]
