# Generated by Django 5.1.15 on 2026-02-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0022_insumo_composicioninsumo_producto_insumos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo Envío (S/)'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento (S/)'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_envio',
            field=models.CharField(blank=True, choices=[('RECOJO', '🏠 Recojo en Taller'), ('MOTORIZADO', '🏍️ Motorizado (Lima)'), ('SHALOM', '🚛 Shalom'), ('OLVA', '📦 Olva Courier'), ('OTRO', '✨ Otro')], default='RECOJO', max_length=50, verbose_name='Método de Envío'),
        ),
    ]
