# Generated by Django 5.1.15 on 2026-02-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_pedido_costo_envio_pedido_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='paga_al_recibir',
            field=models.BooleanField(default=False, verbose_name='Paga Envío al Recibir'),
        ),
    ]
