# Generated by Django 5.1.15 on 2026-02-08 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_pedido_paga_al_recibir'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('progreso', models.PositiveIntegerField(default=0, help_text='Porcentaje 0-100')),
                ('dependencias', models.ManyToManyField(blank=True, to='inventario.tareaproyecto')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='inventario.proyecto')),
            ],
        ),
    ]
