# Generated by Django 5.1.15 on 2026-02-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0025_tareaproyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareaproyecto',
            name='categoria',
            field=models.CharField(choices=[('DISENO', '🎨 Diseño'), ('IMPRESION', '🖨️ Impresión'), ('POST', '🔧 Post-Procesado'), ('ELEC', '⚡ Electrónica'), ('OTROS', '📦 Otros')], default='OTROS', max_length=20),
        ),
    ]
