# Generated by Django 5.1.15 on 2026-02-09 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0026_tareaproyecto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(default='#3b82f6', help_text='Código Hex (ej: #3b82f6)', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='tareaproyecto',
            name='categoria_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.categoriatarea'),
        ),
    ]
