# Generated by Django 5.1.15 on 2026-02-09 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0027_categoriatarea_tareaproyecto_categoria_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareaproyecto',
            name='categoria',
        ),
        migrations.RenameField(
            model_name='tareaproyecto',
            old_name='categoria_new',
            new_name='categoria',
        ),
    ]
