# Generated by Django 5.2.11 on 2026-03-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0029_iteminsumopedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dni',
            field=models.CharField(blank=True, max_length=20, verbose_name='DNI / RUC'),
        ),
    ]
